# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.author_api import AuthorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthorApi(unittest.TestCase):
    """AuthorApi unit test stubs"""

    def setUp(self):
        self.api = AuthorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_author_by_field_author_structured_search_get(self):
        """Test case for get_author_by_field_author_structured_search_get

        search authors by descriptive field names  # noqa: E501
        """
        pass

    def test_get_author_by_syntax_string_author_search_get(self):
        """Test case for get_author_by_syntax_string_author_search_get

        search authors by zbMATH style user query  # noqa: E501
        """
        pass

    def test_get_author_by_zbmath_code_author_code_get(self):
        """Test case for get_author_by_zbmath_code_author_code_get

        get author data by author code  # noqa: E501
        """
        pass

    def test_intro_author_get(self):
        """Test case for intro_author_get

        introduction for user help regarding this endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
