# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.software_api import SoftwareApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSoftwareApi(unittest.TestCase):
    """SoftwareApi unit test stubs"""

    def setUp(self):
        self.api = SoftwareApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_software_by_field_software_structured_search_get(self):
        """Test case for get_software_by_field_software_structured_search_get

        search software meta data by descriptive field names  # noqa: E501
        """
        pass

    def test_get_software_by_id_software_id_get(self):
        """Test case for get_software_by_id_software_id_get

        get software data by software id  # noqa: E501
        """
        pass

    def test_get_software_by_syntax_string_software_search_get(self):
        """Test case for get_software_by_syntax_string_software_search_get

        search software meta data by zbMATH style user query  # noqa: E501
        """
        pass

    def test_intro_software_get(self):
        """Test case for intro_software_get

        introduction for user help regarding this endpoint software  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
