# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_reference_zbmath import AllOfReferenceZbmath  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfReferenceZbmath(unittest.TestCase):
    """AllOfReferenceZbmath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfReferenceZbmath(self):
        """Test AllOfReferenceZbmath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_reference_zbmath.AllOfReferenceZbmath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
