# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.zbmath_api_data_models_display_documents_submodels_state import ZbmathApiDataModelsDisplayDocumentsSubmodelsState  # noqa: E501
from swagger_client.rest import ApiException


class TestZbmathApiDataModelsDisplayDocumentsSubmodelsState(unittest.TestCase):
    """ZbmathApiDataModelsDisplayDocumentsSubmodelsState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZbmathApiDataModelsDisplayDocumentsSubmodelsState(self):
        """Test ZbmathApiDataModelsDisplayDocumentsSubmodelsState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.zbmath_api_data_models_display_documents_submodels_state.ZbmathApiDataModelsDisplayDocumentsSubmodelsState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
