# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.classification_api import ClassificationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClassificationApi(unittest.TestCase):
    """ClassificationApi unit test stubs"""

    def setUp(self):
        self.api = ClassificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_classification_by_msc2020_code_classification_code_get(self):
        """Test case for get_classification_by_msc2020_code_classification_code_get

        get msc2020 code data by code  # noqa: E501
        """
        pass

    def test_get_msc2020_by_field_classification_structured_search_get(self):
        """Test case for get_msc2020_by_field_classification_structured_search_get

        search msc codes meta data by descriptive field names  # noqa: E501
        """
        pass

    def test_get_msc2020_by_syntax_string_classification_search_get(self):
        """Test case for get_msc2020_by_syntax_string_classification_search_get

        search msc codes meta data by zbMATH style user query  # noqa: E501
        """
        pass

    def test_intro_classification_get(self):
        """Test case for intro_classification_get

        introduction for user help regarding this endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
