# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.document_api import DocumentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self):
        self.api = DocumentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_document_by_field_document_structured_search_get(self):
        """Test case for get_document_by_field_document_structured_search_get

        search documents by descriptive field names  # noqa: E501
        """
        pass

    def test_get_document_by_syntax_string_document_search_get(self):
        """Test case for get_document_by_syntax_string_document_search_get

        search documents by zbMATH style user query  # noqa: E501
        """
        pass

    def test_get_document_by_zbmath_id_document_id_get(self):
        """Test case for get_document_by_zbmath_id_document_id_get

        get document data by zbMath ID  # noqa: E501
        """
        pass

    def test_intro_document_get(self):
        """Test case for intro_document_get

        introduction for user help regarding this endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
