# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.serial_api import SerialApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSerialApi(unittest.TestCase):
    """SerialApi unit test stubs"""

    def setUp(self):
        self.api = SerialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_serial_by_field_serial_structured_search_get(self):
        """Test case for get_serial_by_field_serial_structured_search_get

        search serial meta data by descriptive field names  # noqa: E501
        """
        pass

    def test_get_serial_by_id_serial_id_get(self):
        """Test case for get_serial_by_id_serial_id_get

        get serial data by serial id  # noqa: E501
        """
        pass

    def test_get_serial_by_syntax_string_serial_search_get(self):
        """Test case for get_serial_by_syntax_string_serial_search_get

        search serial meta data by zbMATH style user query  # noqa: E501
        """
        pass

    def test_intro_serial_get(self):
        """Test case for intro_serial_get

        introduction for user help regarding this endpoint serial  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
