# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Award(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'wikidata': 'AllOfAwardWikidata',
        'year': 'int'
    }

    attribute_map = {
        'title': 'title',
        'wikidata': 'wikidata',
        'year': 'year'
    }

    def __init__(self, title=None, wikidata=None, year=None):  # noqa: E501
        """Award - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._wikidata = None
        self._year = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if wikidata is not None:
            self.wikidata = wikidata
        if year is not None:
            self.year = year

    @property
    def title(self):
        """Gets the title of this Award.  # noqa: E501


        :return: The title of this Award.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Award.


        :param title: The title of this Award.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def wikidata(self):
        """Gets the wikidata of this Award.  # noqa: E501


        :return: The wikidata of this Award.  # noqa: E501
        :rtype: AllOfAwardWikidata
        """
        return self._wikidata

    @wikidata.setter
    def wikidata(self, wikidata):
        """Sets the wikidata of this Award.


        :param wikidata: The wikidata of this Award.  # noqa: E501
        :type: AllOfAwardWikidata
        """

        self._wikidata = wikidata

    @property
    def year(self):
        """Gets the year of this Award.  # noqa: E501


        :return: The year of this Award.  # noqa: E501
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this Award.


        :param year: The year of this Award.  # noqa: E501
        :type: int
        """

        self._year = year

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Award, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Award):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
