# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EditorialContribution(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reviewer': 'AllOfEditorialContributionReviewer',
        'text': 'str',
        'contribution_type': 'ContributionType'
    }

    attribute_map = {
        'reviewer': 'reviewer',
        'text': 'text',
        'contribution_type': 'contribution_type'
    }

    def __init__(self, reviewer=None, text=None, contribution_type=None):  # noqa: E501
        """EditorialContribution - a model defined in Swagger"""  # noqa: E501
        self._reviewer = None
        self._text = None
        self._contribution_type = None
        self.discriminator = None
        if reviewer is not None:
            self.reviewer = reviewer
        if text is not None:
            self.text = text
        if contribution_type is not None:
            self.contribution_type = contribution_type

    @property
    def reviewer(self):
        """Gets the reviewer of this EditorialContribution.  # noqa: E501


        :return: The reviewer of this EditorialContribution.  # noqa: E501
        :rtype: AllOfEditorialContributionReviewer
        """
        return self._reviewer

    @reviewer.setter
    def reviewer(self, reviewer):
        """Sets the reviewer of this EditorialContribution.


        :param reviewer: The reviewer of this EditorialContribution.  # noqa: E501
        :type: AllOfEditorialContributionReviewer
        """

        self._reviewer = reviewer

    @property
    def text(self):
        """Gets the text of this EditorialContribution.  # noqa: E501


        :return: The text of this EditorialContribution.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this EditorialContribution.


        :param text: The text of this EditorialContribution.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def contribution_type(self):
        """Gets the contribution_type of this EditorialContribution.  # noqa: E501


        :return: The contribution_type of this EditorialContribution.  # noqa: E501
        :rtype: ContributionType
        """
        return self._contribution_type

    @contribution_type.setter
    def contribution_type(self, contribution_type):
        """Sets the contribution_type of this EditorialContribution.


        :param contribution_type: The contribution_type of this EditorialContribution.  # noqa: E501
        :type: ContributionType
        """

        self._contribution_type = contribution_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditorialContribution, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditorialContribution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
