# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Source(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'book': 'list[Book]',
        'pages': 'str',
        'series': 'list[Series]',
        'source': 'str'
    }

    attribute_map = {
        'book': 'book',
        'pages': 'pages',
        'series': 'series',
        'source': 'source'
    }

    def __init__(self, book=None, pages=None, series=None, source=None):  # noqa: E501
        """Source - a model defined in Swagger"""  # noqa: E501
        self._book = None
        self._pages = None
        self._series = None
        self._source = None
        self.discriminator = None
        if book is not None:
            self.book = book
        if pages is not None:
            self.pages = pages
        if series is not None:
            self.series = series
        if source is not None:
            self.source = source

    @property
    def book(self):
        """Gets the book of this Source.  # noqa: E501


        :return: The book of this Source.  # noqa: E501
        :rtype: list[Book]
        """
        return self._book

    @book.setter
    def book(self, book):
        """Sets the book of this Source.


        :param book: The book of this Source.  # noqa: E501
        :type: list[Book]
        """

        self._book = book

    @property
    def pages(self):
        """Gets the pages of this Source.  # noqa: E501


        :return: The pages of this Source.  # noqa: E501
        :rtype: str
        """
        return self._pages

    @pages.setter
    def pages(self, pages):
        """Sets the pages of this Source.


        :param pages: The pages of this Source.  # noqa: E501
        :type: str
        """

        self._pages = pages

    @property
    def series(self):
        """Gets the series of this Source.  # noqa: E501


        :return: The series of this Source.  # noqa: E501
        :rtype: list[Series]
        """
        return self._series

    @series.setter
    def series(self, series):
        """Sets the series of this Source.


        :param series: The series of this Source.  # noqa: E501
        :type: list[Series]
        """

        self._series = series

    @property
    def source(self):
        """Gets the source of this Source.  # noqa: E501


        :return: The source of this Source.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Source.


        :param source: The source of this Source.  # noqa: E501
        :type: str
        """

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Source, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Source):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
