# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Title(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'addition': 'str',
        'original': 'str',
        'subtitle': 'str',
        'title': 'str'
    }

    attribute_map = {
        'addition': 'addition',
        'original': 'original',
        'subtitle': 'subtitle',
        'title': 'title'
    }

    def __init__(self, addition=None, original=None, subtitle=None, title=None):  # noqa: E501
        """Title - a model defined in Swagger"""  # noqa: E501
        self._addition = None
        self._original = None
        self._subtitle = None
        self._title = None
        self.discriminator = None
        if addition is not None:
            self.addition = addition
        if original is not None:
            self.original = original
        if subtitle is not None:
            self.subtitle = subtitle
        if title is not None:
            self.title = title

    @property
    def addition(self):
        """Gets the addition of this Title.  # noqa: E501


        :return: The addition of this Title.  # noqa: E501
        :rtype: str
        """
        return self._addition

    @addition.setter
    def addition(self, addition):
        """Sets the addition of this Title.


        :param addition: The addition of this Title.  # noqa: E501
        :type: str
        """

        self._addition = addition

    @property
    def original(self):
        """Gets the original of this Title.  # noqa: E501


        :return: The original of this Title.  # noqa: E501
        :rtype: str
        """
        return self._original

    @original.setter
    def original(self, original):
        """Sets the original of this Title.


        :param original: The original of this Title.  # noqa: E501
        :type: str
        """

        self._original = original

    @property
    def subtitle(self):
        """Gets the subtitle of this Title.  # noqa: E501


        :return: The subtitle of this Title.  # noqa: E501
        :rtype: str
        """
        return self._subtitle

    @subtitle.setter
    def subtitle(self, subtitle):
        """Sets the subtitle of this Title.


        :param subtitle: The subtitle of this Title.  # noqa: E501
        :type: str
        """

        self._subtitle = subtitle

    @property
    def title(self):
        """Gets the title of this Title.  # noqa: E501


        :return: The title of this Title.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Title.


        :param title: The title of this Title.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Title, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Title):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
