# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Translation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'translated_from': 'list[object]',
        'translated_to': 'list[object]'
    }

    attribute_map = {
        'translated_from': 'translated_from',
        'translated_to': 'translated_to'
    }

    def __init__(self, translated_from=None, translated_to=None):  # noqa: E501
        """Translation - a model defined in Swagger"""  # noqa: E501
        self._translated_from = None
        self._translated_to = None
        self.discriminator = None
        if translated_from is not None:
            self.translated_from = translated_from
        if translated_to is not None:
            self.translated_to = translated_to

    @property
    def translated_from(self):
        """Gets the translated_from of this Translation.  # noqa: E501


        :return: The translated_from of this Translation.  # noqa: E501
        :rtype: list[object]
        """
        return self._translated_from

    @translated_from.setter
    def translated_from(self, translated_from):
        """Sets the translated_from of this Translation.


        :param translated_from: The translated_from of this Translation.  # noqa: E501
        :type: list[object]
        """

        self._translated_from = translated_from

    @property
    def translated_to(self):
        """Gets the translated_to of this Translation.  # noqa: E501


        :return: The translated_to of this Translation.  # noqa: E501
        :rtype: list[object]
        """
        return self._translated_to

    @translated_to.setter
    def translated_to(self, translated_to):
        """Sets the translated_to of this Translation.


        :param translated_to: The translated_to of this Translation.  # noqa: E501
        :type: list[object]
        """

        self._translated_to = translated_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Translation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Translation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
