# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WhichCountry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'country': 'CountryCodes'
    }

    attribute_map = {
        'code': 'code',
        'country': 'country'
    }

    def __init__(self, code=None, country=None):  # noqa: E501
        """WhichCountry - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._country = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if country is not None:
            self.country = country

    @property
    def code(self):
        """Gets the code of this WhichCountry.  # noqa: E501


        :return: The code of this WhichCountry.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this WhichCountry.


        :param code: The code of this WhichCountry.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def country(self):
        """Gets the country of this WhichCountry.  # noqa: E501


        :return: The country of this WhichCountry.  # noqa: E501
        :rtype: CountryCodes
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this WhichCountry.


        :param country: The country of this WhichCountry.  # noqa: E501
        :type: CountryCodes
        """

        self._country = country

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WhichCountry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WhichCountry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
