# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'field': 'str',
        'percent': 'str',
        'percentile': 'str'
    }

    attribute_map = {
        'count': 'count',
        'field': 'field',
        'percent': 'percent',
        'percentile': 'percentile'
    }

    def __init__(self, count=None, field=None, percent=None, percentile=None):  # noqa: E501
        """ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._field = None
        self._percent = None
        self._percentile = None
        self.discriminator = None
        if count is not None:
            self.count = count
        if field is not None:
            self.field = field
        if percent is not None:
            self.percent = percent
        if percentile is not None:
            self.percentile = percentile

    @property
    def count(self):
        """Gets the count of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501


        :return: The count of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.


        :param count: The count of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def field(self):
        """Gets the field of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501


        :return: The field of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.


        :param field: The field of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def percent(self):
        """Gets the percent of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501


        :return: The percent of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :rtype: str
        """
        return self._percent

    @percent.setter
    def percent(self, percent):
        """Sets the percent of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.


        :param percent: The percent of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :type: str
        """

        self._percent = percent

    @property
    def percentile(self):
        """Gets the percentile of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501


        :return: The percentile of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :rtype: str
        """
        return self._percentile

    @percentile.setter
    def percentile(self, percentile):
        """Sets the percentile of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.


        :param percentile: The percentile of this ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField.  # noqa: E501
        :type: str
        """

        self._percentile = percentile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZbmathApiDataModelsDisplayAuthorsSubmodelsMainField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
