# coding: utf-8

"""
    REST API for zbMATH Open

    a REST api for zbMATH Open, currently with endpoints for authors, classifications, documents, serials and software  # noqa: E501

    OpenAPI spec version: v0.4.3rc0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aliases': 'list[object]',
        'checked': 'str',
        'codes': 'list[object]',
        'name': 'str'
    }

    attribute_map = {
        'aliases': 'aliases',
        'checked': 'checked',
        'codes': 'codes',
        'name': 'name'
    }

    def __init__(self, aliases=None, checked=None, codes=None, name=None):  # noqa: E501
        """ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor - a model defined in Swagger"""  # noqa: E501
        self._aliases = None
        self._checked = None
        self._codes = None
        self._name = None
        self.discriminator = None
        if aliases is not None:
            self.aliases = aliases
        if checked is not None:
            self.checked = checked
        if codes is not None:
            self.codes = codes
        if name is not None:
            self.name = name

    @property
    def aliases(self):
        """Gets the aliases of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501


        :return: The aliases of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :rtype: list[object]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.


        :param aliases: The aliases of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :type: list[object]
        """

        self._aliases = aliases

    @property
    def checked(self):
        """Gets the checked of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501


        :return: The checked of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :rtype: str
        """
        return self._checked

    @checked.setter
    def checked(self, checked):
        """Sets the checked of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.


        :param checked: The checked of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :type: str
        """

        self._checked = checked

    @property
    def codes(self):
        """Gets the codes of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501


        :return: The codes of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :rtype: list[object]
        """
        return self._codes

    @codes.setter
    def codes(self, codes):
        """Sets the codes of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.


        :param codes: The codes of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :type: list[object]
        """

        self._codes = codes

    @property
    def name(self):
        """Gets the name of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501


        :return: The name of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.


        :param name: The name of this ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZbmathApiDataModelsDisplayDocumentsSubmodelsAuthor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
